version: "3.7"

services:
  app:
    build:
      args:
        user: gandhi
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: kelasgratis
    container_name: kelasgratis-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - kelasgratis

  db:
    image: mysql:5.7
    container_name: kelasgratis-db # Changed container name to avoid conflict
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - kelasgratis

  nginx:
    image: nginx:alpine
    container_name: kelasgratis-nginx
    restart: unless-stopped
    ports:
      - 8080:80 # Ensure no conflict with port 8000
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - kelasgratis

networks:
  kelasgratis:
    driver: bridge
